export type OfflineAction = { id: string; accountId: string; lane: "merchant_catalog"|"merchant_inventory"|"driver_delivery"; type: string; payload: unknown; createdAt: string; attempts: number };
export type TrackingDelta = { cursor: number; orderId: number; observedAt: string; latitude: number; longitude: number; accuracyM: number|null; etaSeconds: number|null };
const DB = "deliveryplatform-offline-v1";
function request<T>(r: IDBRequest<T>) { return new Promise<T>((resolve,reject)=>{r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);}); }
async function open() { return new Promise<IDBDatabase>((resolve,reject)=>{ const r=indexedDB.open(DB,1); r.onupgradeneeded=()=>{const d=r.result; d.createObjectStore("meta"); const a=d.createObjectStore("actions",{keyPath:"id"});a.createIndex("account","accountId");const x=d.createObjectStore("deltas",{keyPath:["accountId","scope","cursor"]});x.createIndex("accountScope","[accountId,scope]");}; r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);}); }
async function tx<T>(stores:string[],mode:IDBTransactionMode,fn:(t:IDBTransaction)=>Promise<T>) { const d=await open(); try { const t=d.transaction(stores,mode); const v=await fn(t); await new Promise<void>((resolve,reject)=>{t.oncomplete=()=>resolve();t.onerror=()=>reject(t.error);t.onabort=()=>reject(t.error);});return v;} finally {d.close();} }
export async function applyTrackingDeltas(accountId:string,scope:string,deltas:TrackingDelta[]) { if(!accountId||!scope) throw new Error("offline_scope_required"); await tx(["deltas","meta"],"readwrite",async t=>{const s=t.objectStore("deltas"),m=t.objectStore("meta");let max=0;for(const delta of deltas){if(!Number.isSafeInteger(delta.cursor)||delta.cursor<1)throw new Error("invalid_tracking_delta");s.put({...delta,accountId,scope});max=Math.max(max,delta.cursor);}if(max) m.put(max,`cursor:${accountId}:${scope}`);}); }
export async function trackingCursor(accountId:string,scope:string){return tx(["meta"],"readonly",t=>request<number|undefined>(t.objectStore("meta").get(`cursor:${accountId}:${scope}`)).then(v=>v??0));}
export async function enqueueOfflineAction(action:OfflineAction){if(!crypto.randomUUID||!action.id||!action.accountId)throw new Error("offline_action_invalid");await tx(["actions"],"readwrite",async t=>{await request(t.objectStore("actions").add(action));});}
export async function replayOfflineActions(accountId:string,send:(action:OfflineAction)=>Promise<void>){return tx(["actions"],"readwrite",async t=>{const store=t.objectStore("actions"),rows=await request<OfflineAction[]>(store.index("account").getAll(accountId));for(const a of rows.sort((x,y)=>x.createdAt.localeCompare(y.createdAt))){try{await send(a);store.delete(a.id);}catch{store.put({...a,attempts:a.attempts+1});break;}}});}
export async function clearOfflineAccount(accountId:string){await tx(["actions","deltas","meta"],"readwrite",async t=>{for(const n of ["actions","deltas"]){const s=t.objectStore(n);const i=s.index(n==="actions"?"account":"accountScope");const r=i.openCursor(n==="actions"?accountId:IDBKeyRange.bound([accountId,""],[accountId,"\uffff"]));await new Promise<void>((resolve,reject)=>{r.onsuccess=()=>{const c=r.result;if(!c)return resolve();c.delete();c.continue();};r.onerror=()=>reject(r.error);});}t.objectStore("meta").delete(`cursor:${accountId}:admin`);t.objectStore("meta").delete(`cursor:${accountId}:customer`);t.objectStore("meta").delete(`cursor:${accountId}:merchant`);t.objectStore("meta").delete(`cursor:${accountId}:driver`);});}
