apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - prometheus-rules.yaml
  - resilience-invariant-probe-rules.yaml
  - resilience-circuit-breaker-alertmanagerconfig.yaml
  - resilience-matrix-wazuh-escalation-alertmanagerconfig.yaml
commonLabels:
  app.kubernetes.io/managed-by: kustomize
