import * as SQLite from "expo-sqlite";

export type SyncAction = { id: string; accountId: string; lane: "merchant_catalog"|"merchant_inventory"|"driver_delivery"; type: string; payload: string; createdAt: string; attempts: number };
export type SyncDelta = { cursor: number; payload: string };
let database: SQLite.SQLiteDatabase | null = null;
async function db() { if (!database) { database = await SQLite.openDatabaseAsync("deliveryplatform-sync.db"); await database.execAsync("PRAGMA journal_mode=WAL; PRAGMA foreign_keys=ON; CREATE TABLE IF NOT EXISTS sync_meta(account_id TEXT NOT NULL, scope TEXT NOT NULL, cursor INTEGER NOT NULL, PRIMARY KEY(account_id,scope)); CREATE TABLE IF NOT EXISTS sync_delta(account_id TEXT NOT NULL, scope TEXT NOT NULL, cursor INTEGER NOT NULL, payload TEXT NOT NULL, PRIMARY KEY(account_id,scope,cursor)); CREATE TABLE IF NOT EXISTS sync_action(id TEXT PRIMARY KEY, account_id TEXT NOT NULL, lane TEXT NOT NULL, action_type TEXT NOT NULL, payload TEXT NOT NULL, created_at TEXT NOT NULL, attempts INTEGER NOT NULL DEFAULT 0);"); } return database; }
export async function applyDeltas(accountId:string, scope:string, deltas:SyncDelta[]) { const d=await db(); await d.withTransactionAsync(async()=>{let max=0;for(const x of deltas){if(!Number.isSafeInteger(x.cursor)||x.cursor<1)throw new Error("invalid_delta");await d.runAsync("INSERT OR IGNORE INTO sync_delta(account_id,scope,cursor,payload) VALUES(?,?,?,?)",accountId,scope,x.cursor,x.payload);max=Math.max(max,x.cursor);}if(max)await d.runAsync("INSERT INTO sync_meta(account_id,scope,cursor) VALUES(?,?,?) ON CONFLICT(account_id,scope) DO UPDATE SET cursor=MAX(cursor,excluded.cursor)",accountId,scope,max);}); }
export async function cursor(accountId:string,scope:string){const d=await db();const r=await d.getFirstAsync<{cursor:number}>("SELECT cursor FROM sync_meta WHERE account_id=? AND scope=?",accountId,scope);return r?.cursor??0;}
export async function queueAction(a:SyncAction){const d=await db();await d.runAsync("INSERT INTO sync_action(id,account_id,lane,action_type,payload,created_at,attempts) VALUES(?,?,?,?,?,?,?)",a.id,a.accountId,a.lane,a.type,a.payload,a.createdAt,a.attempts);}
export async function replay(accountId:string,send:(a:SyncAction)=>Promise<void>){const d=await db();const rows=await d.getAllAsync<SyncAction>("SELECT id,account_id AS accountId,lane,action_type AS type,payload,created_at AS createdAt,attempts FROM sync_action WHERE account_id=? ORDER BY created_at,id",accountId);for(const a of rows){try{await send(a);await d.runAsync("DELETE FROM sync_action WHERE id=?",a.id);}catch{await d.runAsync("UPDATE sync_action SET attempts=attempts+1 WHERE id=?",a.id);break;}}}
export async function eraseAccount(accountId:string){const d=await db();await d.withTransactionAsync(async()=>{await d.runAsync("DELETE FROM sync_meta WHERE account_id=?",accountId);await d.runAsync("DELETE FROM sync_delta WHERE account_id=?",accountId);await d.runAsync("DELETE FROM sync_action WHERE account_id=?",accountId);});}
