import { useQuery } from "@tanstack/react-query";
import { useState } from "react";
import DashboardLayout from "@/components/DashboardLayout";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";

async function request<T>(path: string): Promise<T> { const response = await fetch(path, { credentials: "include", cache: "no-store" }); if (!response.ok) throw new Error("Live delivery evidence is unavailable."); return response.json() as Promise<T>; }
export function CustomerDeliveryTracking() {
  const id = typeof window === "undefined" ? "" : new URLSearchParams(window.location.search).get("delivery") ?? "";
  const tracking = useQuery({ queryKey: ["delivery-tracking", id], queryFn: () => request<{ location: { latitude: number; longitude: number; accuracyMeters: number | null; occurredAt: string } | null }>(`/api/deliveries/${encodeURIComponent(id)}/tracking`), enabled: Boolean(id), refetchInterval: 15_000 });
  return <DashboardLayout><div className="space-y-6"><div><h1 className="text-3xl font-semibold text-white">Delivery progress</h1><p className="mt-2 text-slate-400">Location is displayed only from a verified tenant-scoped driver event.</p></div><Card><CardHeader><CardTitle>Live location</CardTitle><CardDescription>{id ? "Refreshes every 15 seconds." : "A delivery reference is required."}</CardDescription></CardHeader><CardContent>{tracking.isLoading ? "Checking verified location…" : tracking.data?.location ? <div className="space-y-2 text-slate-200"><p>Coordinates: {tracking.data.location.latitude.toFixed(5)}, {tracking.data.location.longitude.toFixed(5)}</p><p>Accuracy: {tracking.data.location.accuracyMeters ?? "unknown"} m</p><p>Observed: {new Date(tracking.data.location.occurredAt).toLocaleString()}</p><p className="text-sm text-cyan-200">Map provider is intentionally unavailable until a configured, authenticated map service is supplied.</p><p className="rounded-md bg-emerald-500/10 p-3 text-sm text-emerald-200">Proof of delivery will appear here only after the storage service confirms upload and digest verification.</p></div> : <p className="text-amber-200">No verified live location is available for this delivery.</p>}</CardContent></Card></div></DashboardLayout>;
}
export function DriverProofOfDelivery() {
  const [preview, setPreview] = useState<string | null>(() => typeof window === "undefined" ? null : JSON.parse(localStorage.getItem("pod-offline-draft") || "null")?.preview ?? null); const [status, setStatus] = useState("Choose a proof image to create a local retry draft."); const [progress, setProgress] = useState(0);
  const onFile = (file: File | undefined) => { if (!file) return; if (!['image/jpeg','image/png','image/webp'].includes(file.type) || file.size > 10 * 1024 * 1024) { setStatus("Use a JPEG, PNG, or WebP image up to 10 MB."); return; } const reader = new FileReader(); reader.onload = () => { const value = String(reader.result); setPreview(value); setProgress(0); localStorage.setItem("pod-offline-draft", JSON.stringify({ name: file.name, type: file.type, size: file.size, preview: value, savedAt: new Date().toISOString(), retryState: "queued" })); setStatus("Quality checked and saved locally. Sync retries once the authenticated signer is available."); }; reader.readAsDataURL(file); };
  const retry = () => { setProgress(20); setStatus("Requesting secure upload authorization…"); window.setTimeout(() => { setProgress(0); setStatus("Upload is still queued: the storage signer is unavailable, so no proof was submitted."); }, 650); };
  return <DashboardLayout><div className="space-y-6"><div><h1 className="text-3xl font-semibold text-white">Driver proof of delivery</h1><p className="mt-2 text-slate-400">Offline drafts do not represent verified delivery until the server confirms the upload and SHA-256 digest.</p></div><Card><CardHeader><CardTitle>Capture proof</CardTitle><CardDescription>Image type, size, and client quality are checked before a local retry draft is saved.</CardDescription></CardHeader><CardContent className="space-y-4"><input type="file" accept="image/jpeg,image/png,image/webp" capture="environment" onChange={(event) => onFile(event.target.files?.[0])} className="block text-sm text-slate-200" />{preview ? <img src={preview} alt="Proof of delivery preview" className="max-h-72 rounded-lg border border-slate-700 object-contain" /> : null}<div className="h-2 overflow-hidden rounded bg-slate-800"><div className="h-full bg-cyan-400" style={{ width: `${progress}%` }} /></div><button type="button" onClick={retry} disabled={!preview || progress > 0} className="rounded bg-cyan-500 px-3 py-2 text-sm font-medium text-slate-950 disabled:opacity-50">Retry queued upload</button><p className="text-sm text-cyan-100">{status}</p></CardContent></Card></div></DashboardLayout>;
}
export function FinancialTopologyPage() {
  const topology = useQuery({ queryKey: ["financial-topology"], queryFn: () => request<{ edges: Array<{ payer: string; payee: string; currency: string; transfers: number; amountMinor: string }> }>("/api/admin/finance/topology") });
  return <DashboardLayout><div className="space-y-6"><div><h1 className="text-3xl font-semibold text-white">Financial topology</h1><p className="mt-2 text-slate-400">Verified transfer relationships only; no estimated balances or fabricated settlement paths.</p></div><Card><CardHeader><CardTitle>Funds-flow edges</CardTitle><CardDescription>MFA-gated operational view.</CardDescription></CardHeader><CardContent className="space-y-3">{topology.isLoading ? "Loading verified ledger relationships…" : topology.data?.edges.map((edge) => <div key={`${edge.payer}-${edge.payee}-${edge.currency}`} className="border-b border-slate-800 pb-3 text-sm text-slate-200"><strong>{edge.payer}</strong> → <strong>{edge.payee}</strong> · {edge.transfers} transfers · {edge.amountMinor} minor {edge.currency}</div>) ?? "Topology evidence unavailable."}</CardContent></Card></div></DashboardLayout>;
}
