import { useQuery } from "@tanstack/react-query";
import DashboardLayout from "@/components/DashboardLayout";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";

async function request<T>(path: string): Promise<T> { const response = await fetch(path, { credentials: "include", cache: "no-store" }); if (!response.ok) throw new Error("Live delivery evidence is unavailable."); return response.json() as Promise<T>; }
export function CustomerDeliveryTracking() {
  const id = typeof window === "undefined" ? "" : new URLSearchParams(window.location.search).get("delivery") ?? "";
  const tracking = useQuery({ queryKey: ["delivery-tracking", id], queryFn: () => request<{ location: { latitude: number; longitude: number; accuracyMeters: number | null; occurredAt: string } | null }>(`/api/deliveries/${encodeURIComponent(id)}/tracking`), enabled: Boolean(id), refetchInterval: 15_000 });
  return <DashboardLayout><div className="space-y-6"><div><h1 className="text-3xl font-semibold text-white">Delivery progress</h1><p className="mt-2 text-slate-400">Location is displayed only from a verified tenant-scoped driver event.</p></div><Card><CardHeader><CardTitle>Live location</CardTitle><CardDescription>{id ? "Refreshes every 15 seconds." : "A delivery reference is required."}</CardDescription></CardHeader><CardContent>{tracking.isLoading ? "Checking verified location…" : tracking.data?.location ? <div className="space-y-2 text-slate-200"><p>Coordinates: {tracking.data.location.latitude.toFixed(5)}, {tracking.data.location.longitude.toFixed(5)}</p><p>Accuracy: {tracking.data.location.accuracyMeters ?? "unknown"} m</p><p>Observed: {new Date(tracking.data.location.occurredAt).toLocaleString()}</p><p className="text-sm text-cyan-200">Map provider is intentionally unavailable until a configured, authenticated map service is supplied.</p></div> : <p className="text-amber-200">No verified live location is available for this delivery.</p>}</CardContent></Card></div></DashboardLayout>;
}
export function FinancialTopologyPage() {
  const topology = useQuery({ queryKey: ["financial-topology"], queryFn: () => request<{ edges: Array<{ payer: string; payee: string; currency: string; transfers: number; amountMinor: string }> }>("/api/admin/finance/topology") });
  return <DashboardLayout><div className="space-y-6"><div><h1 className="text-3xl font-semibold text-white">Financial topology</h1><p className="mt-2 text-slate-400">Verified transfer relationships only; no estimated balances or fabricated settlement paths.</p></div><Card><CardHeader><CardTitle>Funds-flow edges</CardTitle><CardDescription>MFA-gated operational view.</CardDescription></CardHeader><CardContent className="space-y-3">{topology.isLoading ? "Loading verified ledger relationships…" : topology.data?.edges.map((edge) => <div key={`${edge.payer}-${edge.payee}-${edge.currency}`} className="border-b border-slate-800 pb-3 text-sm text-slate-200"><strong>{edge.payer}</strong> → <strong>{edge.payee}</strong> · {edge.transfers} transfers · {edge.amountMinor} minor {edge.currency}</div>) ?? "Topology evidence unavailable."}</CardContent></Card></div></DashboardLayout>;
}
