import { useMutation, useQuery } from "@tanstack/react-query";
import { useMemo, useState } from "react";
import { Activity, AlertTriangle, BellRing, DatabaseZap, FlaskConical, Landmark, RefreshCw, Search, ShieldCheck } from "lucide-react";

type FinancialOverview = { immutableIdentityEnforced: boolean; retrievedAt: string; immutableTransfers: Array<{ transferId: string; payerFsp: string; payeeFsp: string; amountMinor: string; currency: string; state: string; updatedAt: string }>; inconsistentReconciliations: Array<{ id: string; transferId: string; transferState: string; platformRefundedMinor: string; platformNetSettledMinor: string; createdAt: string }> };
type HealthStatus = "reachable" | "unhealthy" | "unreachable" | "unconfigured";
type Health = { dependencies: Array<{ name: string; status: HealthStatus; checkedAt: string; latencyMs: number | null }>; history: Array<{ dependency: "tigerbeetle" | "temporal"; status: HealthStatus; latencyMs: number | null; observedAt: string }>; retrievedAt: string };
type Simulations = { enabled: boolean; productionBlocked: boolean; scenarios: string[] };
type Alert = { id: string; severity: "warning" | "critical"; source: "reconciliation" | "dependency"; title: string; detail: string; createdAt: string };

async function fetchAdmin<T>(path: string): Promise<T> { const response = await fetch(path, { credentials: "include", cache: "no-store" }); if (!response.ok) throw new Error((await response.json().catch(() => ({ error: "request_failed" }))).error ?? "request_failed"); return response.json() as Promise<T>; }
const statusClass = (status: HealthStatus) => status === "reachable" ? "border-emerald-400/30 bg-emerald-400/10 text-emerald-200" : status === "unconfigured" ? "border-slate-600 bg-slate-800 text-slate-300" : "border-rose-400/30 bg-rose-400/10 text-rose-100";

function Trend({ label, values }: { label: string; values: Health["history"] }) {
  if (!values.length) return <div className="rounded-xl border border-slate-800 bg-slate-950/40 p-4 text-sm text-slate-400">{label}: no persisted observations yet.</div>;
  const highestLatency = Math.max(1, ...values.map((item) => item.latencyMs ?? 0));
  return <div className="rounded-xl border border-slate-800 bg-slate-950/40 p-4"><div className="flex items-center justify-between text-sm"><span className="font-medium text-slate-200">{label}</span><span className="text-slate-500">Last {values.length} observations</span></div><div className="mt-4 flex h-16 items-end gap-1" aria-label={`${label} uptime trend`}>{values.map((point) => <div key={point.observedAt} title={`${point.status} at ${new Date(point.observedAt).toLocaleString()}`} className={point.status === "reachable" ? "bg-emerald-400" : point.status === "unconfigured" ? "bg-slate-500" : "bg-rose-400"} style={{ height: `${Math.max(12, ((point.latencyMs ?? highestLatency) / highestLatency) * 100)}%`, width: `${Math.max(4, 100 / values.length - 1)}%` }} />)}</div></div>;
}

export default function FinancialAdministration() {
  const [query, setQuery] = useState(""); const [startDate, setStartDate] = useState(""); const [endDate, setEndDate] = useState(""); const [sort, setSort] = useState("updated_desc");
  const filterQuery = useMemo(() => new URLSearchParams(Object.entries({ query, startDate, endDate, sort }).filter(([, value]) => value)).toString(), [query, startDate, endDate, sort]);
  const overview = useQuery({ queryKey: ["finance-admin-overview", filterQuery], queryFn: () => fetchAdmin<FinancialOverview>(`/api/admin/finance/overview?${filterQuery}`), refetchInterval: 20_000 });
  const health = useQuery({ queryKey: ["finance-admin-health"], queryFn: () => fetchAdmin<Health>("/api/admin/finance/health"), refetchInterval: 15_000 });
  const alerts = useQuery({ queryKey: ["finance-admin-alerts"], queryFn: () => fetchAdmin<{ alerts: Alert[] }>("/api/admin/finance/alerts"), refetchInterval: 15_000 });
  const simulations = useQuery({ queryKey: ["finance-admin-simulations"], queryFn: () => fetchAdmin<Simulations>("/api/admin/finance/simulations") });
  const simulation = useMutation({ mutationFn: async (scenario: string) => { const response = await fetch(`/api/admin/finance/simulations/${scenario}`, { method: "POST", credentials: "include" }); if (!response.ok) throw new Error((await response.json().catch(() => ({ error: "simulation_unavailable" }))).error ?? "simulation_unavailable"); return response.json() as Promise<{ scenario: string; status: string }>; } });
  const accessError = [overview.error, health.error, alerts.error, simulations.error].find(Boolean) as Error | undefined;
  const history = health.data?.history ?? [];
  if (accessError) return <section className="mx-auto max-w-3xl rounded-2xl border border-rose-400/30 bg-rose-400/10 p-8 text-rose-100"><ShieldCheck className="mb-4 h-8 w-8" /><h1 className="text-2xl font-semibold">Financial administration is restricted</h1><p className="mt-3 leading-7">This workspace requires an authenticated platform financial administrator with verified MFA. {accessError.message.replace(/_/g, " ")}.</p></section>;
  return <div className="space-y-6">
    <header className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex items-center gap-2 text-cyan-200"><Landmark className="h-5 w-5" />Financial administration</div><h1 className="mt-2 text-3xl font-semibold text-white">Immutable funds oversight</h1><p className="mt-2 max-w-3xl leading-7 text-slate-300">Read-only transfer evidence, reconciliation warnings, and dependency health. This workspace cannot alter funds.</p></div><button type="button" onClick={() => { void overview.refetch(); void health.refetch(); void alerts.refetch(); }} className="inline-flex items-center gap-2 rounded-lg border border-slate-700 bg-slate-900 px-4 py-2 text-sm text-slate-100 hover:border-cyan-400/50"><RefreshCw className="h-4 w-4" />Refresh</button></header>
    <section className="grid gap-4 md:grid-cols-3"><div className="rounded-2xl border border-emerald-400/30 bg-emerald-400/10 p-5"><ShieldCheck className="h-5 w-5 text-emerald-200" /><div className="mt-3 text-sm text-emerald-100">Financial identity</div><div className="mt-1 text-xl font-semibold text-white">{overview.data?.immutableIdentityEnforced ? "Immutable" : "Unavailable"}</div></div><div className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><DatabaseZap className="h-5 w-5 text-cyan-200" /><div className="mt-3 text-sm text-slate-300">Filtered transfers</div><div className="mt-1 text-xl font-semibold text-white">{overview.data?.immutableTransfers.length ?? "—"}</div></div><div className="rounded-2xl border border-amber-400/30 bg-amber-400/10 p-5"><AlertTriangle className="h-5 w-5 text-amber-200" /><div className="mt-3 text-sm text-amber-100">Open warnings</div><div className="mt-1 text-xl font-semibold text-white">{alerts.data?.alerts.length ?? "—"}</div></div></section>
    <section className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><div className="mb-4 flex items-center gap-2"><BellRing className="h-5 w-5 text-amber-200" /><div><h2 className="font-semibold text-white">Notification center</h2><p className="text-sm text-slate-400">Refreshes every 15 seconds with reconciliation and dependency warnings.</p></div></div><div className="space-y-2">{alerts.data?.alerts.length ? alerts.data.alerts.map((alert) => <div key={alert.id} className={`rounded-xl border p-3 ${alert.severity === "critical" ? "border-rose-400/30 bg-rose-400/10" : "border-amber-400/30 bg-amber-400/10"}`}><div className="flex justify-between gap-3"><span className="font-medium text-white">{alert.title}</span><span className="text-xs text-slate-300">{new Date(alert.createdAt).toLocaleString()}</span></div><p className="mt-1 text-sm text-slate-200">{alert.detail}</p></div>) : <p className="text-sm text-slate-400">No active reconciliation or dependency warnings are recorded.</p>}</div></section>
    <section className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><div className="mb-4 flex items-center gap-2"><Activity className="h-5 w-5 text-cyan-200" /><div><h2 className="font-semibold text-white">Dependency health</h2><p className="text-sm text-slate-400">Color-coded current checks and persisted 24-hour observations.</p></div></div><div className="grid gap-3 md:grid-cols-2">{health.data?.dependencies.map((dependency) => <div key={dependency.name} className={`rounded-xl border p-4 ${statusClass(dependency.status)}`}><div className="flex items-center justify-between gap-2"><span className="font-medium">{dependency.name}</span><span className="text-xs uppercase tracking-wide">{dependency.status}</span></div><div className="mt-2 text-xs opacity-80">Checked {new Date(dependency.checkedAt).toLocaleTimeString()} · {dependency.latencyMs === null ? "no endpoint configured" : `${dependency.latencyMs} ms`}</div></div>)}</div><div className="mt-4 grid gap-3 md:grid-cols-2"><Trend label="TigerBeetle adapter uptime" values={history.filter((point) => point.dependency === "tigerbeetle")} /><Trend label="Temporal bridge uptime" values={history.filter((point) => point.dependency === "temporal")} /></div></section>
    <section className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><div className="mb-4 flex items-center gap-2"><Search className="h-5 w-5 text-cyan-200" /><div><h2 className="font-semibold text-white">Find immutable financial records</h2><p className="text-sm text-slate-400">Search is bounded to 100 characters and the service returns no more than 100 matching records.</p></div></div><div className="grid gap-3 md:grid-cols-4"><label className="md:col-span-2"><span className="sr-only">Search transfers</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Transfer ID, FSP, or state" className="w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-sm text-white" /></label><input aria-label="Start date" type="date" value={startDate} onChange={(event) => setStartDate(event.target.value)} className="rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-sm text-white" /><input aria-label="End date" type="date" value={endDate} onChange={(event) => setEndDate(event.target.value)} className="rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-sm text-white" /><select aria-label="Sort records" value={sort} onChange={(event) => setSort(event.target.value)} className="rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-sm text-white"><option value="updated_desc">Newest updated</option><option value="updated_asc">Oldest updated</option><option value="created_desc">Newest created</option><option value="created_asc">Oldest created</option></select></div></section>
    <section className="overflow-x-auto rounded-2xl border border-slate-800 bg-slate-900"><div className="border-b border-slate-800 px-5 py-4"><h2 className="font-semibold text-white">Immutable transfer records</h2><p className="mt-1 text-sm text-slate-400">Monetary amounts are stored in minor units.</p></div><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-slate-950/60 text-xs uppercase tracking-wide text-slate-400"><tr><th className="px-5 py-3">Transfer</th><th className="px-5 py-3">Parties</th><th className="px-5 py-3">Minor units</th><th className="px-5 py-3">State</th><th className="px-5 py-3">Updated</th></tr></thead><tbody>{overview.data?.immutableTransfers.map((transfer) => <tr key={transfer.transferId} className="border-t border-slate-800 text-slate-200"><td className="px-5 py-3 font-mono text-xs">{transfer.transferId}</td><td className="px-5 py-3">{transfer.payerFsp} → {transfer.payeeFsp}</td><td className="px-5 py-3">{transfer.amountMinor} {transfer.currency}</td><td className="px-5 py-3">{transfer.state}</td><td className="px-5 py-3 text-slate-400">{new Date(transfer.updatedAt).toLocaleString()}</td></tr>)}</tbody></table></section>
    <section className="rounded-2xl border border-rose-400/30 bg-rose-400/5 p-5"><h2 className="font-semibold text-rose-100">Failed-refund reconciliation events</h2><p className="mt-1 text-sm text-rose-200/80">Any record below requires investigation before settlement or customer communication.</p><div className="mt-4 space-y-2">{overview.data?.inconsistentReconciliations.length ? overview.data.inconsistentReconciliations.map((event) => <div key={event.id} className="rounded-lg border border-rose-400/20 bg-slate-950/40 p-3 text-sm text-slate-200"><span className="font-mono text-xs">{event.transferId}</span> · {event.transferState} · refunded {event.platformRefundedMinor} · net {event.platformNetSettledMinor} · {new Date(event.createdAt).toLocaleString()}</div>) : <p className="text-sm text-slate-400">No inconsistent reconciliation events are currently recorded.</p>}</div></section>
    <section className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><div className="mb-4 flex items-center gap-2"><FlaskConical className="h-5 w-5 text-violet-200" /><div><h2 className="font-semibold text-white">Isolated recovery scenarios</h2><p className="mt-1 text-sm text-slate-400">Controls remain disabled unless an explicit non-production executor is configured.</p></div></div><div className="flex flex-wrap gap-3">{simulations.data?.scenarios.map((scenario) => <button key={scenario} type="button" disabled={!simulations.data.enabled || simulation.isPending} onClick={() => simulation.mutate(scenario)} className="rounded-lg border border-violet-400/30 bg-violet-400/10 px-4 py-2 text-sm text-violet-100 disabled:cursor-not-allowed disabled:opacity-40">Run {scenario.replace(/-/g, " ")}</button>)}</div>{simulation.isError && <p role="alert" className="mt-4 text-sm text-rose-200">Simulation was not submitted: {(simulation.error as Error).message.replace(/_/g, " ")}.</p>}{simulation.data && <p role="status" className="mt-4 text-sm text-emerald-200">{simulation.data.scenario} scenario submitted to the isolated executor.</p>}</section>
  </div>;
}
