apiVersion: v1
kind: ServiceAccount
metadata:
  name: resilience-k6-runner
  namespace: resilience-test
  labels:
    app.kubernetes.io/name: resilience-k6-runner
    app.kubernetes.io/part-of: delivery-platform-resilience-testing
    resilience.delivery-platform.io/environment: non-production
automountServiceAccountToken: false
