export const ENV = {
  appId: process.env.APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  oAuthClientId: process.env.OAUTH_CLIENT_ID ?? "",
  oAuthClientSecret: process.env.OAUTH_CLIENT_SECRET ?? "",
  oAuthTokenPath: process.env.OAUTH_TOKEN_PATH ?? "/oauth/token",
  oAuthUserInfoPath: process.env.OAUTH_USERINFO_PATH ?? "/oauth/userinfo",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  objectStorageEndpoint: process.env.OBJECT_STORAGE_ENDPOINT ?? "",
  objectStorageRegion: process.env.OBJECT_STORAGE_REGION ?? "us-east-1",
  objectStorageBucket: process.env.OBJECT_STORAGE_BUCKET ?? "",
  objectStorageAccessKeyId: process.env.OBJECT_STORAGE_ACCESS_KEY_ID ?? "",
  objectStorageSecretAccessKey: process.env.OBJECT_STORAGE_SECRET_ACCESS_KEY ?? "",
  objectStorageForcePathStyle: process.env.OBJECT_STORAGE_FORCE_PATH_STYLE !== "false",
  aiGatewayBaseUrl: process.env.AI_GATEWAY_BASE_URL ?? "",
  aiGatewayApiKey: process.env.AI_GATEWAY_API_KEY ?? "",
  notificationWebhookUrl: process.env.NOTIFICATION_WEBHOOK_URL ?? "",
  notificationWebhookToken: process.env.NOTIFICATION_WEBHOOK_TOKEN ?? "",
};
