apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    kubernetes.io/metadata.name: monitoring
    resilience.delivery-platform.io/environment: non-production
---
apiVersion: v1
kind: Namespace
metadata:
  name: resilience-test
  labels:
    kubernetes.io/metadata.name: resilience-test
    resilience.delivery-platform.io/environment: non-production
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
