apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - security
  - pricing-dispatch
  - central
  - go-services
  - python-services
commonLabels:
  app.kubernetes.io/part-of: deliveryplatform
  app.kubernetes.io/managed-by: kustomize
