apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - workloads.yaml
commonLabels:
  app.kubernetes.io/part-of: deliveryplatform
  app.kubernetes.io/managed-by: kustomize
  deliveryplatform.io/autoscaling-alternative: prometheus-adapter
